report file in root dir on GHA

diff --git a/.github/workflows/ppc64le-runtime.yaml b/.github/workflows/ppc64le-runtime.yaml
--- a/.github/workflows/ppc64le-runtime.yaml
+++ b/.github/workflows/ppc64le-runtime.yaml
@@ -4,7 +4,7 @@ on:
   issue_comment:
     types: [created, edited]
   schedule:
-    - cron: '0 6 * * 1'
+    - cron: '0 6 * * *'
   workflow_dispatch:
 
 permissions:
@@ -179,35 +179,72 @@ jobs:
           else
             echo "found=false" >> $GITHUB_OUTPUT
           fi
-      - name: Comment test summary on PR
-        if: github.event.issue.pull_request && steps.script-check.outputs.found == 'true'
-        uses: actions/github-script@v6
+      
+      - name: Set workflow status summary
+        run: |
+          # TRIGGER_DATE=$(date -u +"%Y-%m-%d")
+          # START_TIME="${{ needs.ppc64le-runtime-build-test.outputs.workflow_start_time }}"
+          # END_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
+          # BUILD_STATUS="${{ needs.ppc64le-runtime-build-test.result }}"
+          # TEST_STATUS="${{ needs.ppc64le-runtime-build-test.result }}"
+          # cat <<EOF >> workflow_status.txt
+          # Trigger Date: ${TRIGGER_DATE}
+          # Start Time: ${START_TIME}
+          # End Time: ${END_TIME}
+          # Build Status: ${BUILD_STATUS}
+          # Test Status: ${TEST_STATUS}
+          cat Script-details >> workflow_status
+          echo "------------------------------------------------------------------" >> workflow_status
+          # EOF
+          cat workflow_status
+      
+      - name: Generate GitHub App token
+        id: app-token
+        uses: actions/create-github-app-token@v1
         with:
-          github-token: ${{ secrets.PPC64LE_GITHUB_TOKEN }}
-          script: |
-            const fs = require('fs');
-            const body = fs.readFileSync('Script-details', 'utf8');
-            const issue_number = context.issue.number;
-            await github.rest.issues.createComment({
-              issue_number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body
-            });
-      - name: Comment failure message on PR
-        if: steps.check-status.outputs.status != 'success' || steps.script-check.outputs.found == 'false'
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.PPC64LE_GITHUB_TOKEN }}
-          script: |
-            const runId = process.env.GITHUB_RUN_ID;
-            const repo = process.env.GITHUB_REPOSITORY;
-            const jobUrl = `https://github.com/${repo}/actions/runs/${runId}`;
-            const issue_number = context.issue.number;
-            const body = `The ppc64le runtime build and test job has failed. Below is the link.\n${jobUrl}`;
-            await github.rest.issues.createComment({
-              issue_number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body
-            });
+          app-id: ${{ secrets.APP_ID }}
+          private-key: ${{ secrets.APP_PRIVATE_KEY }}
+  
+      - name: Commit workflow_status.txt to repo
+        run: |
+          pwd
+          ls -la
+          ls -la ../
+          git config user.name "github-app[bot]"
+          git config user.email "github-app[bot]@users.noreply.github.com"
+          git add workflow_status.txt
+          git commit -m "Add ppc64le workflow status summary" || echo "No changes to commit"
+          git push
+    
+      # - name: Comment test summary on PR
+      #   if: github.event.issue.pull_request && steps.script-check.outputs.found == 'true'
+      #   uses: actions/github-script@v6
+      #   with:
+      #     github-token: ${{ secrets.PPC64LE_GITHUB_TOKEN }}
+      #     script: |
+      #       const fs = require('fs');
+      #       const body = fs.readFileSync('Script-details', 'utf8');
+      #       const issue_number = context.issue.number;
+      #       await github.rest.issues.createComment({
+      #         issue_number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body
+      #       });
+      # - name: Comment failure message on PR
+      #   if: steps.check-status.outputs.status != 'success' || steps.script-check.outputs.found == 'false'
+      #   uses: actions/github-script@v6
+      #   with:
+      #     github-token: ${{ secrets.PPC64LE_GITHUB_TOKEN }}
+      #     script: |
+      #       const runId = process.env.GITHUB_RUN_ID;
+      #       const repo = process.env.GITHUB_REPOSITORY;
+      #       const jobUrl = `https://github.com/${repo}/actions/runs/${runId}`;
+      #       const issue_number = context.issue.number;
+      #       const body = `The ppc64le runtime build and test job has failed. Below is the link.\n${jobUrl}`;
+      #       await github.rest.issues.createComment({
+      #         issue_number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body
+      #       });
